.TH internsctl 1 "2023-12-19" "Arush Sharma" "internsctl Manual Page"
.SH NAME
internsctl - A custom command

.SH SYNOPSIS
internsctl [command] [options]

.SH DESCRIPTION
internsctl is a custom command with version $INTERNSCTL_VERSION. 

...

.SH COMMANDS
* -- version: Display the version number of internsctl.

.SH OPTIONS
...

.SH EXAMPLES
internsctl --version

.SH SEE ALSO
...

.SH AUTHOR
Your Name

.SH BUGS
Please report any bugs to <mydemoemail@gmail.com>

.SH HISTORY
* v0.1.0 (2023-12-19): Initial release.

.AE